name: Sr Barriga comes around

on:
  schedule:
    - cron: "23 06 24 * *"

jobs:
  execute:
    env:
      MONGO_URI: ${{secrets.MONGO_URI}}
      SPOTIFY_VALUE: ${{secrets.SPOTIFY_VALUE}} 
      API_TELEGRAM: ${{secrets.API_TELEGRAM}} 
      BOT_KEY: ${{secrets.BOT_KEY}} 
      CHAT_ID: ${{secrets.CHAT_ID}}
    
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
    
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Sr Barriga charges everyone
        run: make run-charge
